on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "${{ vars.AWS_REGION }}"
  ## ...
  
jobs:
    Terraform:
        name: 'S3 State Bucket'
        runs-on: ubuntu-24.04
        environment: production
        defaults:
            run:
                shell: bash
                #working-directory: ../../Terraform_AWS_Services/terraform-state-s3-locking-bucket
        steps:
        - name: Checkout
          uses: actions/checkout@v4
           # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
        - name: Cache plugin dir
          uses: actions/cache@v4
          with:
            path: ~/.tflint.d/plugins
            key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
        - name: Setup TFLint
          uses: terraform-linters/setup-tflint@v4
          with:
            tflint_version: v0.52.0
        - name: 'Show version'
          run: tflint --version
        - name: Init TFLint
          run: tflint --init
          env:
              # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
            GITHUB_TOKEN: ${{ github.token }}
        - name: Run TFLint on specific directory
          run: tflint --chdir=../../Terraform_AWS_Services/terraform-state-s3-locking-bucket -f compact
       