on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "${{ vars.AWS_REGION }}"
  ## ...
  
jobs:
    Terraform:
        name: 'S3 State Bucket'
        runs-on: ubuntu-24.04
        environment: production
        defaults:
            run:
                shell: bash
                working-directory: ../../Terraform_AWS_Services/terraform-state-s3-locking-bucket
        steps:
        - name: Checkout
          uses: actions/checkout@v4
       